<a href="https://colab.research.google.com/github/KoSeoAh/ML_2022/blob/main/mid_term.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#3주차 Code

# 필요한 라이브러리들 import & 데이터 읽고 프린트 (key)

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_iris
iris_dataset=load_iris()

print("iris_dataset의 키:\n", iris_dataset.keys())



iris_dataset의 키:
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [7]:
#데이터 프린트 (sample data)

# data의 처음 다섯 행
print(iris_dataset['data'][:5])

# data의 처음 다섯 행 (시각화하여 출력)
import seaborn as sns 
iris_dataset2=sns.load_dataset('iris')
iris_dataset2.head()



[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
#데이터 프린트 (target_names, feature_names, target)

print(iris_dataset['target_names'])
print(iris_dataset['feature_names'])
print(iris_dataset['target'])
print(type(iris_dataset['target']))
print(iris_dataset['target'].shape)

['setosa' 'versicolor' 'virginica']
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
<class 'numpy.ndarray'>
(150,)


In [6]:
#데이터 분리(학습데이터, 테스트데이터)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'],random_state=0)

print(X_train.shape)
print(X_test.shape)
print(type(X_train.shape))
print(type(X_test.shape))

print(y_train.shape)
print(y_test.shape)
print(type(y_train.shape))
print(type(y_test.shape))

(112, 4)
(38, 4)
<class 'tuple'>
<class 'tuple'>
(112,)
(38,)
<class 'tuple'>
<class 'tuple'>


In [11]:
#코랩에서 드라이브 마운트

!pip install mglearn
from google.colab import drive
drive.mount('/content/drive')

import mglearn

     |████████████████████████████████| 540 kB 5.1 MB/s 
  Created wheel for mglearn: filename=mglearn-0.1.9-py2.py3-none-any.whl size=582639 sha256=0b2dbb7d28a235141f62c86f450c21be0e5783ffdaa7d3dcb6a740f6c802ef5d
  Stored in directory: /root/.cache/pip/wheels/f1/17/e1/1720d6dcd70187b6b6c3750cb3508798f2b1d57c9d3214b08b
Successfully built mglearn
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [12]:
# 드라이브에서 폴더 생성 후 깃허브 코드 클론

from google.colab import drive
drive.mount('/content/drive')
!cd "/content/drive"
!cd "/content/drive/My drive/Example"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/bin/bash: line 0: cd: /content/drive/My drive/Example: No such file or directory
